### ISSUE TITLE
Release of NVMeDirect 2.0

### ISSUE THREAD

**Issue by shirshen12** [nvmedirect/nvmedirect#11]
Hi,

Is there a plan to release the NVMeDirect 2.0 toolkit, as described in this paper; https://www.flashmemorysummit.com/English/Collaterals/Proceedings/2017/20170810_FA31_Kim.pdf

**Comment by hyeongjunkim** [comment]
Hi,

NVMeDirect 2.0 will be released as open source, as described in FMS slide.
However, the release is delayed due to additional works such as bug fixes.
I expect to release the framework in late Nov, or early Dec.

Thanks.

\- Hyeong-Jun Kim

**Comment by shirshen12** [comment]
Thanks! Will check back then. Closing it.
