### ISSUE TITLE
Python API for NVMeDirect 1.0 and 2.0

### ISSUE THREAD

**Issue by shirshen12** [nvmedirect/nvmedirect#12]
Hi,

Is there a plan for releasing a Python (2.7 preferably) for NVMeDirect 1.0 and 2.0 like Micron uNVMe toolkit; https://github.com/MicronSSD/unvme

**Comment by hyeongjunkim** [comment]
Hi @shirshen12,

We do not have plan for releasing a Python version.

Thanks.
\- Hyeong-Jun Kim

**Comment by shirshen12** [comment]
Ok, can you please let me know what are the developer workflow for committing code to the NVMeDirect repository. Do you/will you accept a python wrapper for your userspace API. I can wrap it using ctypes or cffi.

**Comment by hyeongjunkim** [comment]
Thank you for your contribution to the development of the NVMeDirect framework.
Because the framework is being developed by myself alone, there is no special developer workflow.
If you create a pull requests, then I will review and accept your requests.

Thanks.
\- Hyeong-Jun Kim

**Comment by shirisalwaysure** [comment]
Sounds good. Closing.
