### ISSUE TITLE
NVMeDirect2.0 and More Test Examples

### ISSUE THREAD

**Issue by hustliyilin** [nvmedirect/nvmedirect#14]
Thanks for your NVMeDirect1.0 . Where can I get NVMeDirect2.0 source code?Could you give more test examples, Just like Redis source code in your paper（HotStorage 2016 NVMeDirect: A User-space I/O Framework for Application-specific Optimization on NVMe SSDs）?

**Comment by cdcsl** [comment]
Hi.

NVMeDirect 2.0 is due for release some time next month.

With regards to the examples, we will upload a few with NVMeDirect 2.0.

Thanks.
