### ISSUE TITLE
kallsyms_lookup_name return type looks incorrect

### ISSUE THREAD

**Issue by iamchanghyunpark** [nvmedirect/nvmedirect#16]
There are various [uses](https://github.com/nvmedirect/nvmedirect/blob/1e9dee599550fa3cc8fb8a885bbcd561611cb7fb/modules/nvmed-core.c#L786) of `kallsyms_lookup_name()` in the project, and the returned value is saved in an `int` format.

However, I think the purpose of the `kallsyms_lookup_name()` is to retrieve the code address of the requested symbol, and so it should be in the `unsigned long` form, or at least a type of 64bits (`int` is 32 bits). 

The `kallsyms_lookup_name()` [source code](https://elixir.free-electrons.com/linux/latest/source/kernel/kallsyms.c#L197) shows a `unsigned long` return type.

**Comment by cdcsl** [comment]
Hi.

Thanks for reporting this. I'll get back to you after I've had a look at it.

**Comment by cdcsl** [comment]
Hi.

This should be fixed in c2cb416.

Thanks again for the report.
