### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by chenxuqiang** [nvmedirect/nvmedirect#17]
nvmedirect//library/lib_nvmed.c 1607:if(cache->lpaddr >= start_block && end_block <= cache->lpaddr).
my question is why it is end_block <= cache->lpaddr, I think it should be cache->lpaddr <= end_block, because I think cache->lpaddr should be in [start_block, end_block]. Maybe I was wrong, so I want to know why it is end_block <= cache->lpaddr.
(sorry, my english is not good enough, and I hope you can understand what I mean.)

**Comment by cdcsl** [comment]
Hi.

Thanks for the report. I'll let you know when I've had a look at it.

**Comment by hyeongjunkim** [comment]
@chenxuqiang 
Thanks for your report.
This issue was reflected in my local repository, but it was not uploaded here.

I uploaded code (including what you mentioned) that improved buffer I / O. 

Thank you very much and Sorry to late reply.
