### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by cmicalizzi** [nvmedirect/nvmedirect#27]
Looks like no work has been done on this in a while. Current version doesn't compile on kernels after 4.12. Is this project defunct or on hiatus?

thank you

chuck

**Comment by hyeongjunkim** [comment]
Hello. cmicalizzi

Thank for your ping.
As you mentioned, This project has been inactive for a long time.
Now I'm working on the next plan. but.. To be honest, I'm looking for the direction of this project.
(It may take some times. ^^)

Please let me know, if you have any idea or requests on this project.

Thanks.
