### ISSUE TITLE
FIO test script

### ISSUE THREAD

**Issue by leonidravich** [nvmedirect/nvmedirect#4]
trying to run FIO benchmark 

[global]
name=rand_w
filename=/dev/nvme17n1
ioengine=sync
direct=1
bs=4k
rw=randwrite
numjobs=1
size=4096m
runtime=1
thread

[job1]
name=nvmed
rw=randread
ioengine=nvmed_aio
iodepth=16

but do not see any statistics from FIO

./fio nvme_test.script 
nvmed: (g=0): rw=randread, bs=4K-4K/4K-4K/4K-4K, ioengine=nvmed_aio, iodepth=16
fio-2.2.10
Starting 1 thread
Jobs: 1 (f=1): [r(1)] [0.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 14d:03h:48m:51s]
^Cbs: 1 (f=1): [r(1)] [0.0% done] [0KB/0KB/0KB /s] [0/0/0 iops] [eta 38d:10h:21m:11s]

**Comment by hyeongjunkim** [comment]
Sorry for the delay.
We uploaded new FIO plugin for NVMeDirect and example script.
Please test with new plugin.
Thanks.
