### ISSUE TITLE
make and make install is having errors

### ISSUE THREAD

**Issue by visheshvijay** [nvmedirect/nvmedirect#8]
Hi,

I am having Rhel_7.0 with updated kernel of 4.11
I tried to make and make install but I am facing issues with it :

terminal logs attached
[terminal_logs.txt](https://github.com/nvmedirect/nvmedirect/files/1018800/terminal_logs.txt)

Thanks,
Vishesh

**Comment by hyeongjunkim** [comment]
The module is correctly compiled on ubuntu 14.04 with kernel of 4.11.
I do not have a Rhel. So, it is hard to identify the exact problem on Rhel7.
However, all errors in the attached logs appear as functions related to credentials.
I found that the header for credential(linux/cred.h) is not included on source code of module.
I added missing code and uploaded b9758ee.

Please download the latest codes and test it.

Lastly, NVMeDirect supports official Kernel released on http://www.kernel.org.
Please confirm that you are using the official kernel.

Thanks.
\- Hyeong-Jun Kim

**Comment by visheshvijay** [comment]
Yes I am using latest official kernel 4.11

**Comment by visheshvijay** [comment]
Hi Kim,

Now with the latest build I am able to make and make install.
Can i create any number of queues with this module. By default the inbox nvme driver creates queues per core means 
e.g.if there are 8 cpu then 8 IO SQ-CQ will be created.

Can i create 100 IO queues with this nvmed module if yes please let me know the command for creating 100 IO queues

I tried this command also 

_[root@jaguar54 nvmedirect-master]# nvmed_admin /dev/nvme0n1 set 32
nvmed_admin: error while loading shared libraries: libnvmed.so: cannot open shared object file: No such file or directory
[root@jaguar54 nvmedirect-master]# nvmed_admin /dev/nvme0n1 set root 32
nvmed_admin: error while loading shared libraries: libnvmed.so: cannot open shared object file: No such file or directory
[root@jaguar54 nvmedirect-master]#_

-Vishesh

**Comment by hyeongjunkim** [comment]
You can create I/O queues up to the maximum number of devices supported.
For example, if you use Intel 750 series, you can create 32 queues (including created by the inbox nvme driver).
And if you using Samsung 950 Pro, you can create up to 8 queues.
If the device supports 100 I/O queues, you can do it.
The APIs for managing I/O queue are described on API documents. [APIs](https://github.com/nvmedirect/nvmedirect/blob/master/NVMeDirect-APIs.md)

By default, the shared library for NVMeDirect framework is installed on /usr/local/lib.
I guess RHEL does not scan that directory by default.
Try
`sudo sh -c "echo /usr/local/lib > /etc/ld.so.conf.d/third_party.conf"`
`sudo ldconfig`
and re-execute the _nvmed_admin_ command.

\- Hyeong-Jun Kim

**Comment by jinsoox** [comment]
Vishesh,
You can check out the maximum number of queues supported by your device by running the "nvmed_info" tool available at https://github.com/nvmedirect/nvmed_info. After installing it, simply run the following command:
$ sudo ./nvmed_info /dev/nvme0n1 all | grep NSQA

**Comment by visheshvijay** [comment]
Hi Kim,

Thanks for the command but still I am unable to access the drive
[root@jaguar54 sbin]# nvmed_admin /dev/nvme0n1 set root 32
/dev/nvme0n1: fail to open nvme device file
Can't access to device

Please guide

-Vishesh

**Comment by visheshvijay** [comment]
One more question i have that after loading nvmed module will the block device come as /dev/nvmed0n1 or same as before /dev/nvme0n1

I have attached the terminal prints Can you please confirm if module is properly loaded
[terminal_prints.txt](https://github.com/nvmedirect/nvmedirect/files/1026158/terminal_prints.txt)

**Comment by hyeongjunkim** [comment]
Vishesh,
After loading module, the block device same as before - /dev/nvme0n1.
Instead of creating special block device for nvmed, NVMeDirect create proc directory for access nvme device in user space.

Could you confirm _**/proc/nvmed/nvme0n1**_ directory is created?
If the module is installed normally, admin file and sysfs symlink are created.
Also, _**NVMeDirect: Module Initialized**_ is displayed on dmesg.

Now, I'm downloading RHEL 7.0.
I will try NVMeDirect on RHEL 7.0 and kernel 4.11.

**Comment by hyeongjunkim** [comment]
Hi Vishesh,
I tested NVMeDirect on RHEL 7.0 and kernel 4.11 and confirmed that it works normally.

Please confirm that _/proc/nvmed/nvme0n1_ directory is created and _NVMeDirect: Module Initialized_ message is displayed on dmesg, after install module using `modprobe nvmed` command.

**Comment by visheshvijay** [comment]
Hi KIm,

The /proc/nvmed/nvme0n1 directory was not created after installing modprobe nvmed
dmesg prints 
[May30 12:53] nvmed: loading out-of-tree module taints kernel.
[  +0.013191] nvme nvme0: pci function 0000:04:00.0
[  +0.000118] nvme nvme1: pci function 0000:05:00.0
[  +0.027350] NVMeDirect: Module Initialized

Terminal prints 
[root@jaguar54 nvmedirect-master]# modprobe nvmed
[root@jaguar54 nvmedirect-master]# uname -a
Linux jaguar54.toshiba-tsip.com 4.11.0 #1 SMP Sat May 6 12:19:12 IST 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@jaguar54 nvmedirect-master]# cat /proc/nvmed/
cat: /proc/nvmed/: Is a directory
[root@jaguar54 nvmedirect-master]# ll /proc/nvmed
total 0
[root@jaguar54 nvmedirect-master]# cd /proc/nvmed/
[root@jaguar54 nvmed]# ll
total 0
[root@jaguar54 nvmed]#

Thanks,
Vishesh

**Comment by hyeongjunkim** [comment]
Hi Vishesh

Before loading the NVMeDirect module using modprobe command,
NVMe module should be installed and the initialization process must be completed.

\# modprobe nvme
\# ls /dev/nvme*
/dev/nvme0  /dev/nvme0n1  /dev/nvme1  /dev/nvme1n1
**(Please confirm all namespace is displayed. After that, install the nvmed module.)**
\# modprobe nvmed
\# ls /proc/nvmed/

\- Hyeong-Jun Kim

**Comment by visheshvijay** [comment]
I followed the exact steps you mentioned but still i dont see any directory created under /proc/nvmed

[root@jaguar54 nvmed]# modprobe nvme
[root@jaguar54 nvmed]# ls /dev/nvme*
/dev/nvme0  /dev/nvme0n1  /dev/nvme1  /dev/nvme1n1
[root@jaguar54 nvmed]# modprobe nvmed
[root@jaguar54 nvmed]# ls /proc/nvmed/
[root@jaguar54 nvmed]#

**Comment by visheshvijay** [comment]
[root@jaguar54 modules]# cd /proc/nvmed/
[root@jaguar54 nvmed]# ll
total 0
dr-xr-xr-x. 2 root root 0 May 30 14:59 nvme0n1
dr-xr-xr-x. 2 root root 0 May 30 14:59 nvme1n1
[root@jaguar54 nvmed]# nvmed_admin /dev/nvme0n1 set root 32
NVMeDirect - /dev/nvme0n1: root => max:32 used:0
[root@jaguar54 nvmed]#


it worked now thanks :)

**Comment by hyeongjunkim** [comment]
Thank you for your testing and feedback :)
Now, I will close this issue.

Thanks.

\- Hyeong-Jun Kim
