### ISSUE TITLE
Cant compile NVMeDirect 1.0 on RHEL 7.3 (Maipo)

### ISSUE THREAD

**Issue by shirshen12** [nvmedirect/nvmedirect#9]
Hi,

I am not able to compile NVMeDirect 1.0 on:

uname -r
3.10.0-514.21.1.el7.x86_64

uname -a
Linux <nodename> 3.10.0-514.21.1.el7.x86_64 #1 SMP Sat Apr 22 02:41:35 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

Can you please me ?

**Comment by hyeongjunkim** [comment]
NVMeDirect supports official Kernel released on http://www.kernel.org.
Please confirm that you are using the official kernel.
It will be helpful if you refer to Issue #8.

Thanks.
\- Hyeong-Jun Kim

**Comment by shirshen12** [comment]
I will check and let you know. I have looked at #8 and I will try to replicate the issue and post the logs in here.

**Comment by hustliyilin** [comment]
Thanks for your NVMeDirect1.0 . Where can I get NVMeDirect2.0 source code?Could you give more test examples, Just like Redis source code in your paper（HotStorage 2016 NVMeDirect: A User-space I/O Framework for Application-specific Optimization on NVMe SSDs）?

**Comment by clicx** [comment]
this is because nvme.h, defined support kernel >= 4.4
while centos series are 2.x to 3.x..

**Comment by cdcsl** [comment]
Hi.

As it's been a while now with no progress on this, I'm going to close it. Please open a new issue if you still require help.

Thanks.

**Comment by cdcsl** [comment]
Hi.

As it's been a while now with no progress on this, I'm going to close it. Please open a new issue if you still require help.

Thanks.
